Improve performance
reg-viz/reg-cli-report-ui pull request #13
Opened 2019-09-11 01:59 UTC by Quramy

## What does this change?

A clear and concise description of what the changes is.

## References

- If you have links to other resources, please list them here. (e.g. issue url, related pull request url, documents)

## Screenshots

If applicable, add screenshots to help explain your changes.

## What can I check for bug fixes?

Please briefly describe how you can confirm the resolution of the bug.

2019-09-12 17:17 UTC, Quramy commented on webpack.config.js
> +      disableHostCheck: true,
I changed devServer config to access from my iOS devices

2019-09-13 04:19 UTC, wadackel requested changes
@Quramy 

Thank you for wonderful work :pray:
I wrote a comment about the details :+1:

2019-09-13 04:19 UTC, wadackel commented on package.json
> +    "@juggle/resize-observer": "^2.3.0",
Would you please using from `polyfill.io` ? So, because if you don't need polyfill, the JavaScript size to execute is small.

2019-09-13 04:19 UTC, wadackel commented on develop/index_large_data.html
> +    <script src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserverEntry%2CIntersectionObserver"></script>
```suggestion
    <script src="https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver%2CIntersectionObserverEntry%2CIntersectionObserver"></script>
```

2019-09-13 04:19 UTC, wadackel commented on src/components/VGrid/VGrid.tsx
> +    document.addEventListener('scroll', this.handleOnScroll);
```suggestion
    document.addEventListener('scroll', this.handleOnScroll, { passive: true });
```

I want to enable `passive` for scroll event that don't need to call `preventDefault` :dog:

2019-09-13 04:19 UTC, wadackel commented on src/components/VGrid/VGrid.tsx
> +    document.removeEventListener('scroll', this.handleOnScroll);
```suggestion
    document.removeEventListener('scroll', this.handleOnScroll, { passive: true });
```

2019-09-13 13:11 UTC, Quramy commented on src/components/VGrid/VGrid.tsx
> +    document.removeEventListener('scroll', this.handleOnScroll);
`removeEventListener` does not accept `passive` options. 🤔 

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#Parameters

2019-09-13 13:12 UTC, Quramy commented
@tsuyoshiwada Thanks for your review and I've fixed your pointed.

2019-09-13 14:12 UTC, wadackel approved these changes
Thank you for fixing!
LGTM :+1:

2019-09-13 14:12 UTC, tsuyoshiwada commented on src/components/VGrid/VGrid.tsx
> +    document.removeEventListener('scroll', this.handleOnScroll);
Oh sorry, I'm wrong. Thanks!

2019-09-13 14:13 UTC, merged